/ouster/metadata:
  history: keep_last
  depth: 1
  reliability: reliable
  durability: transient_local

/os_node/metadata:
  history: keep_last
  depth: 1
  reliability: reliable
  durability: transient_local
