# [Not recommended] Use this configuration only when utilizing the disjointed
# os_sensor and os_cloud configuration
# For the future and for better results consider migrating to combined node/component os_driver
# and utilize the driver_params.yaml along with it. 
ouster/os_sensor:
  ros__parameters:
    sensor_hostname: ''
    udp_dest: ''
    mtp_dest: ''
    mtp_main: false
    lidar_mode: ''
    timestamp_mode: ''
    udp_profile_lidar: ''
    metadata: ''
    lidar_port: 0
    imu_port: 0
ouster/os_cloud:
  ros__parameters:
    sensor_frame: os_sensor
    lidar_frame: os_lidar
    imu_frame: os_imu
    point_cloud_frame: os_lidar
    timestamp_mode: ''  # this value needs to match os_sensor/timestamp_mode
    proc_mask: PCL|SCAN # select PCL and SCAN or either
